In [1]:
import pandas as pd

caminho_arquivo = "../data/raw/itens_raw.csv"

df = pd.read_csv(caminho_arquivo)

df.head()

,versao,coletado_em_utc,item_id,nome,descricao_texto,descricao_original,resumo,preco_combinacao_ouro,preco_total_ouro,preco_venda_ouro,...,FlatHPPoolMod,FlatHPRegenMod,FlatMPPoolMod,FlatMagicDamageMod,FlatMovementSpeedMod,FlatPhysicalDamageMod,FlatSpellBlockMod,PercentAttackSpeedMod,PercentLifeStealMod,PercentMovementSpeedMod
0,16.19.1,2026-09-25T01:42:44.216Z,1001,Botas,25 de Velocidade de Movimento,<mainText><stats><attention>25</attention> de ...,Aumenta levemente a Velocidade de Movimento,300,300,210,...,NaN,NaN,NaN,NaN,25.0,NaN,NaN,NaN,NaN,NaN
1,16.19.1,2026-09-25T01:42:44.216Z,1004,Amuleto da Fada,50% de Regeneração de Mana base,<mainText><stats><attention>50%</attention> de...,Aumenta levemente a Regeneração de Mana,200,200,140,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,16.19.1,2026-09-25T01:42:44.216Z,1006,Pérola do Rejuvenescimento,100% de Regeneração de Vida base,<mainText><stats><attention>100%</attention> d...,Aumenta levemente a Regeneração de Vida,300,300,120,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,16.19.1,2026-09-25T01:42:44.216Z,1011,Cinto do Gigante,350 de Vida,<mainText><stats><attention>350</attention> de...,Aumenta drasticamente a Vida,500,900,630,...,350.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,16.19.1,2026-09-25T01:42:44.216Z,1018,Capa da Agilidade,15% de Chance de Acerto Crítico,<mainText><stats><attention>15%</attention> de...,Aumenta a Chance de Acerto Crítico,600,600,420,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [2]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 254 entries, 0 to 253
Data columns (total 34 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   versao                   254 non-null    str
 1   coletado_em_utc          254 non-null    str
 2   item_id                  254 non-null    int64
 3   nome                     254 non-null    str
 4   descricao_texto          253 non-null    str
 5   descricao_original       253 non-null    str
 6   resumo                   142 non-null    str
 7   preco_combinacao_ouro    254 non-null    int64
 8   preco_total_ouro         254 non-null    int64
 9   preco_venda_ouro         254 non-null    int64
 10  componentes_ids_json     191 non-null    str
 11  evolui_para_ids_json     73 non-null     str
 12  categorias_json          254 non-null    str
 13  atributos_json           254 non-null    str
 14  efeitos_json             37 non-null     str
 15  mapa_summoners_rift      254 non-null    bool
 16  compravel                254 non-null    bool
 17  oculto_da_loja           254 non-null    bool
 18  nivel_receita            191 non-null    float64
 19  campeao_requerido        3 non-null      str
 20  imagem_url               254 non-null    str
 21  fonte_url                254 non-null    str
 22  FlatArmorMod             34 non-null     float64
 23  FlatCritChanceMod        19 non-null     float64
 24  FlatHPPoolMod            89 non-null     float64
 25  FlatHPRegenMod           2 non-null      float64
 26  FlatMPPoolMod            23 non-null     float64
 27  FlatMagicDamageMod       68 non-null     float64
 28  FlatMovementSpeedMod     15 non-null     float64
 29  FlatPhysicalDamageMod    69 non-null     float64
 30  FlatSpellBlockMod        28 non-null     float64
 31  PercentAttackSpeedMod    27 non-null     float64
 32  PercentLifeStealMod      7 non-null      float64
 33  PercentMovementSpeedMod  25 non-null     float64
dtypes: bool(3), float64(13), int64(4), str(14)
memory usage: 62.4 KB

In [3]:
df['categorias_json']

0                                              ["Boots"]
1                                          ["ManaRegen"]
2                                        ["HealthRegen"]
3                                             ["Health"]
4                                     ["CriticalStrike"]
                             ...
249       ["Health","SpellDamage","Mana","AbilityHaste"]
250    ["Damage","NonbootsMovement","MagicPenetration...
251                ["Armor","SpellDamage","MagicResist"]
252    ["Damage","SpellDamage","MagicPenetration","Ar...
253       ["Damage","CriticalStrike","ArmorPenetration"]
Name: categorias_json, Length: 254, dtype: str

In [4]:
# Colunas selecionadas para visão simplificada dos itens.

colunas_selecionadas = [
    'item_id',
    'nome',
    'descricao_texto',
    'categorias_json',
    'preco_total_ouro'
]

df_itens=df[colunas_selecionadas].copy()

df_itens.head()

,item_id,nome,descricao_texto,categorias_json,preco_total_ouro
0,1001,Botas,25 de Velocidade de Movimento,"[""Boots""]",300
1,1004,Amuleto da Fada,50% de Regeneração de Mana base,"[""ManaRegen""]",200
2,1006,Pérola do Rejuvenescimento,100% de Regeneração de Vida base,"[""HealthRegen""]",300
3,1011,Cinto do Gigante,350 de Vida,"[""Health""]",900
4,1018,Capa da Agilidade,15% de Chance de Acerto Crítico,"[""CriticalStrike""]",600

In [5]:
df_itens.info()

<class 'pandas.DataFrame'>
RangeIndex: 254 entries, 0 to 253
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   item_id           254 non-null    int64
 1   nome              254 non-null    str
 2   descricao_texto   253 non-null    str
 3   categorias_json   254 non-null    str
 4   preco_total_ouro  254 non-null    int64
dtypes: int64(2), str(3)
memory usage: 10.1 KB

In [6]:
import json

# Converte as strings formatadas em JSON para listas reais e expande os elementos em novas linhas

df_itens['categorias_json'] = df_itens['categorias_json'].apply(json.loads)
df_itens_explodidos = df_itens[['item_id','categorias_json']].explode('categorias_json')
df_itens_explodidos

     item_id   categorias_json
0       1001             Boots
1       1004         ManaRegen
2       1006       HealthRegen
3       1011            Health
4       1018    CriticalStrike
..       ...               ...
252   667112  MagicPenetration
252   667112  ArmorPenetration
253   667666            Damage
253   667666    CriticalStrike
253   667666  ArmorPenetration

[834 rows x 2 columns]

In [7]:
df_itens_explodidos['categorias_json'] = df_itens_explodidos['categorias_json'].fillna("Item Quebrado")

In [8]:
categorias_unicas = df_itens_explodidos['categorias_json'].unique()
categorias_unicas

<StringArray>
[            'Boots',         'ManaRegen',       'HealthRegen',
            'Health',    'CriticalStrike',       'SpellDamage',
              'Mana',             'Armor',        'SpellBlock',
            'Damage',              'Lane',       'AttackSpeed',
             'OnHit',         'LifeSteal',         'SpellVamp',
            'Jungle',        'Consumable', 'CooldownReduction',
  'ArmorPenetration',            'Active',           'Stealth',
            'Vision',  'NonbootsMovement',      'AbilityHaste',
          'Tenacity',     'Item Quebrado',  'MagicPenetration',
              'Aura',              'Slow',       'MagicResist',
           'Trinket',           'GoldPer']
Length: 32, dtype: str

In [12]:
df_categorias_unicas = pd.DataFrame(categorias_unicas, columns=['nome_categoria']).reset_index()
df_categorias_unicas = df_categorias_unicas.rename(columns={'index':'id_categoria'})
df_categorias_unicas['id_categoria'] += 1
df_categorias_unicas.head()

   id_categoria  nome_categoria
0             1           Boots
1             2       ManaRegen
2             3     HealthRegen
3             4          Health
4             5  CriticalStrike

In [14]:
df_item_categoria = pd.merge(
    df_itens_explodidos,
    df_categorias_unicas,
    left_on='categorias_json',
    right_on='nome_categoria',
    how='inner'
)

df_item_categoria=df_item_categoria[['item_id','id_categoria']]

df_item_categoria = df_item_categoria.drop_duplicates().reset_index(drop=True)
df_item_categoria

     item_id  id_categoria
0       1001             1
1       1004             2
2       1006             3
3       1011             4
4       1018             5
..       ...           ...
829   667112            27
830   667112            19
831   667666            10
832   667666             5
833   667666            19

[834 rows x 2 columns]

In [16]:
colunas_finais_item = ['item_id','nome','preco_total_ouro','descricao_texto']
df_tabela_item = df_itens[colunas_finais_item].copy()

df_tabela_item = df_tabela_item.rename(columns={
    'preco_total_ouro':'preco_unitario',
    'descricao_texto':'descricao'
})

df_tabela_item = df_tabela_item.drop_duplicates(subset=['item_id']).reset_index(drop=True)

df_tabela_item.head()

,item_id,nome,preco_unitario,descricao
0,1001,Botas,300,25 de Velocidade de Movimento
1,1004,Amuleto da Fada,200,50% de Regeneração de Mana base
2,1006,Pérola do Rejuvenescimento,300,100% de Regeneração de Vida base
3,1011,Cinto do Gigante,900,350 de Vida
4,1018,Capa da Agilidade,600,15% de Chance de Acerto Crítico

In [ ]:
elos = [
    'Ferro', 'Bronze', 'Prata', 'Ouro', 
    'Platina', 'Esmeralda', 'Diamante', 
    'Mestre', 'Grão-Mestre', 'Desafiante'
]

df_elo = pd.DataFrame(elos,columns=['elo']).reset_index()
df_elo = df_elo.rename(columns = {'index': 'id_elo'})
df_elo['id_elo'] += 1

df_elo

   id_elo          elo
0       1        Ferro
1       2       Bronze
2       3        Prata
3       4         Ouro
4       5      Platina
5       6    Esmeralda
6       7     Diamante
7       8       Mestre
8       9  Grão-Mestre
9      10   Desafiante

In [21]:
import random

random.seed(42)

nicks = [
    'Faker', 'ShowMaker', 'Chovy', 'Caps', 'Rekkles',
    'BrTT', 'Kami', 'Tinowns', 'Robo', 'Cariok',
    'Titan', 'Aegis', 'Ceos', 'Route', 'Dynquedo',
    'Jojo', 'TitaN', 'Gvoy', 'Damage', 'Wizer',
    'Crocodilo', 'Smeb', 'BeryL', 'Deft', 'Keria'
]

In [22]:
dados_jogadores = []
for index, nick in enumerate (nicks,start=1):
    dados_jogadores.append({
        'id_jogador' : index,
        'nick' : nick,
        'id_elo': random.randint(1,10)
    })
df_jogador = pd.DataFrame(dados_jogadores)
df_jogador.head(10)

   id_jogador       nick  id_elo
0           1      Faker       2
1           2  ShowMaker       1
2           3      Chovy       5
3           4       Caps       4
4           5    Rekkles       4
5           6       BrTT       3
6           7       Kami       2
7           8    Tinowns       9
8           9       Robo       2
9          10     Cariok      10

In [23]:
partidas = []
resultados = ['Vitoria','Derrota']
for i in range(1,21):
    partidas.append({
        'id_partida': i,
        'duracao_minutos': random.randint(18,45),
        'resultado': random.choice(resultados)
    })

df_partida = pd.DataFrame(partidas)
df_partida

    id_partida  duracao_minutos resultado
0            1               36   Derrota
1            2               43   Vitoria
2            3               42   Vitoria
3            4               40   Derrota
4            5               28   Derrota
5            6               22   Vitoria
6            7               42   Derrota
7            8               21   Vitoria
8            9               30   Vitoria
9           10               29   Derrota
10          11               37   Derrota
11          12               43   Vitoria
12          13               41   Derrota
13          14               35   Vitoria
14          15               30   Vitoria
15          16               35   Derrota
16          17               44   Derrota
17          18               36   Vitoria
18          19               40   Vitoria
19          20               19   Vitoria

In [24]:
itens_ids_validos = df_tabela_item['item_id'].tolist()
jogadores_ids_validos = df_jogador['id_jogador'].tolist()
partidas_ids_validos = df_partida['id_partida'].tolist()

compras = []
id_compra = 1

for id_partida in partidas_ids_validos:
    participantes = random.sample(jogadores_ids_validos, 10)

    for jogador in participantes:
        quantidade_itens = random.randint(2,5)
        for _ in range(quantidade_itens):
            compras.append({
                'id_compra':id_compra,
                'id_jogador':jogador,
                'id_item':random.choice(itens_ids_validos),
                'id_partida':id_partida,
                'minuto_compra':random.randint(1,35)
            })
            id_compra += 1

df_compra = pd.DataFrame(compras)
df_compra.head()

   id_compra  id_jogador  id_item  id_partida  minuto_compra
0          1          25     3073           1             14
1          2          25     3865           1             18
2          3          25     4401           1              5
3          4          25     3222           1             11
4          5          10     2065           1             30

In [25]:
import os

caminho_processados = '../data/processed'
os.makedirs(caminho_processados, exist_ok=True)

df_elo.to_csv(f"{caminho_processados}/elo.csv", index=False)
df_jogador.to_csv(f"{caminho_processados}/jogador.csv", index=False)
df_tabela_item.to_csv(f"{caminho_processados}/item.csv", index=False)
df_categorias_unicas.to_csv(f"{caminho_processados}/categoria.csv", index=False)
df_item_categoria.to_csv(f"{caminho_processados}/item_categoria.csv", index=False)
df_partida.to_csv(f"{caminho_processados}/partida.csv", index=False)
df_compra.to_csv(f"{caminho_processados}/compra.csv", index=False)

print("Todos os ficheiros CSV foram esportados para data/processed/!")

Todos os ficheiros CSV foram esportados para data/processed/!